services:
  # 聊天應用服務
  chat-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - ENCRYPTION_KEY=secure-encryption-key-for-development
    depends_on:
      - mongo
      - redis

  # MongoDB 服務
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # Redis 用於會話管理和 Socket.IO 適配器
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mongo-data: